version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: chalk
    update-types: ["version-update:semver-major"]
  - dependency-name: eslint
    update-types: ["version-update:semver-major"]
  - dependency-name: eslint-plugin-promise
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "chore"
