version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: chalk
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.0
