version: 2
updates:
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: monthly
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: chalk
    update-types: ["version-update:semver-major"]
  - dependency-name: eslint
    update-types: ["version-update:semver-major"]
  - dependency-name: eslint-plugin-promise
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "chore"

- package-ecosystem: npm
  directory: "/clients/javascript/express"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: npm
  directory: "/clients/javascript/node-plain"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: npm
  directory: "/clients/typescript"
  schedule:
    interval: monthly
  ignore:
  - dependency-name: typescript
    update-types: ["version-update:semver-major"]
  commit-message:
    prefix: "chore"

- package-ecosystem: pip
  directory: "/clients/python/flask-server"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: gomod
  directory: "/clients/go"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: cargo
  directory: "/clients/rust"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: maven
  directory: "/clients/java/java-httpserver"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: maven
  directory: "/clients/java/java-spark"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"

- package-ecosystem: maven
  directory: "/clients/java/java-springboot"
  schedule:
    interval: monthly
  commit-message:
    prefix: "chore"
