plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.20'
    id 'application'
}

repositories {
    mavenCentral()
}

group = 'extreme-carpaccio'
version = '1.0.0'

dependencies {
    implementation 'io.ktor:ktor-server-core-jvm:3.2.3'
    implementation 'io.ktor:ktor-server-netty-jvm:3.2.3'

    testImplementation 'io.ktor:ktor-server-test-host-jvm:3.2.3'
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'xcarpaccio.MyServerKt'
}

tasks.test {
    useJUnitPlatform()
}
