#ifndef EXTREME_CARPACCIO_CLIENT_HTTPCONFIG_HPP
#define EXTREME_CARPACCIO_CLIENT_HTTPCONFIG_HPP

#define HTTP_SERVER_IP "127.0.0.1"
#define HTTP_SERVER_PORT 8081

#endif // EXTREME_CARPACCIO_CLIENT_HTTPCONFIG_HPP