source "https://rubygems.org"

ruby ">= 3.2"

gem "rails", "~> 8.1.4"
gem "puma", ">= 8.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end
