name: Client Python (Flask)

on:
  pull_request:
    paths:
      - 'clients/python/flask-server/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-python-flask:
    name: Client Python (Flask)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip
    - run: pip install -r requirements.txt && python -m unittest discover -s tests
      working-directory: clients/python/flask-server
