name: Client Erlang

on:
  pull_request:
    paths:
      - 'clients/erlang/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-erlang:
    name: Client Erlang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        rebar3-version: 3.27.1
    - run: rebar3 eunit
      working-directory: clients/erlang
