name: Client Go

on:
  pull_request:
    paths:
      - 'clients/go/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-go:
    name: Client Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: clients/go/go.mod
        cache-dependency-path: clients/go/go.mod
    - run: go test -v ./...
      working-directory: clients/go
