name: Clients Tests

on:
  pull_request:
    paths:
      - 'clients/javascript/**'
      - 'clients/typescript/**'
      - '.github/workflows/on-prs-made-against-clients.yml'

jobs:
  test-javascript-express:
    name: JavaScript Express Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: clients/javascript/express/package-lock.json
      - run: npm install && npm test
        working-directory: clients/javascript/express

  test-javascript-node-plain:
    name: JavaScript Node Plain Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: clients/javascript/node-plain/package-lock.json
      - run: npm install && npm test
        working-directory: clients/javascript/node-plain

  test-typescript:
    name: TypeScript Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: clients/typescript/package-lock.json
      - run: npm install && npm test
        working-directory: clients/typescript
