name: Server (Linux)

on:
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  server-linux:
    name: Server (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
        cache-dependency-path: server/package-lock.json
    - run: npm install && npm run lint && npm test
      working-directory: server
  server-windows:
    name: Server (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
        cache-dependency-path: server/package-lock.json
    - run: npm install && npm run lint && npm test
      working-directory: server
