name: Client Racket

on:
  pull_request:
    paths:
      - 'clients/racket/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-racket:
    name: Client Racket
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Racket
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends racket
    - run: raco test tests/
      working-directory: clients/racket
