name: Client JS (Express)

on:
  pull_request:
    paths:
      - 'clients/javascript/express/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-js-express:
    name: Client JS (Express)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
        cache-dependency-path: clients/javascript/express/package-lock.json
    - run: npm install && npm test
      working-directory: clients/javascript/express
