name: Client Scala

on:
  pull_request:
    paths:
      - 'clients/scala/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-scala:
    name: Client Scala
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - uses: sbt/setup-sbt@v1
    - run: sbt test
      working-directory: clients/scala
