name: Client Ruby (Sinatra)

on:
  pull_request:
    paths:
      - 'clients/ruby/sinatra/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-ruby-sinatra:
    name: Client Ruby (Sinatra)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
        working-directory: clients/ruby/sinatra
    - run: bundle exec rake test
      working-directory: clients/ruby/sinatra
