name: Client Java (JDK HTTP Server)

on:
  pull_request:
    paths:
      - 'clients/java/java-httpserver/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-java-httpserver:
    name: Client Java (JDK HTTP Server)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: maven
        cache-dependency-path: clients/java/java-httpserver/pom.xml
    - run: mvn test
      working-directory: clients/java/java-httpserver
