name: Client Haskell

on:
  pull_request:
    paths:
      - 'clients/haskell/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-haskell:
    name: Client Haskell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
    - run: cabal test
      working-directory: clients/haskell
