name: Client C#

on:
  pull_request:
    paths:
      - 'clients/c#/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-csharp:
    name: Client C#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - run: dotnet test extreme-carpaccio-client-csharp.sln
      working-directory: clients/c#
