name: Client Ruby (Rails)

on:
  pull_request:
    paths:
      - 'clients/ruby/ruby-rails/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-ruby-rails:
    name: Client Ruby (Rails)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
        working-directory: clients/ruby/ruby-rails
    - run: bin/rails test
      working-directory: clients/ruby/ruby-rails
