name: Client PHP

on:
  pull_request:
    paths:
      - 'clients/php/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-php:
    name: Client PHP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        coverage: none
    - run: composer install --no-interaction --no-progress
      working-directory: clients/php
    - run: composer test
      working-directory: clients/php
