name: Client TypeScript

on:
  pull_request:
    paths:
      - 'clients/typescript/**'
      - '.github/workflows/**'
      - '.github/actions/**'

jobs:
  client-ts:
    name: Client TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: npm
        cache-dependency-path: clients/typescript/package-lock.json
    - run: npm install && npm test
      working-directory: clients/typescript
